# Generated by Django 2.2.5 on 2020-09-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200924_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
